### ISSUE TITLE
PDF  PROYECTO FINAL

### ISSUE THREAD

**Issue by Edwin38H** [SistemasTecTlaxiaco/proyecto-final-edwin38h#2]
[Tiendita.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-final-edwin38h/files/6785754/Tiendita.pdf)

**Comment by CxrlosMX** [comment]
Calificación obtenida: 80

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
